CREATE DATABASE tacos_db;
USE tacos_db;

CREATE TABLE tacos (
id int NOT NULL AUTO_INCREMENT,
taco_name VARCHAR(255) NOT NULL,
shell VARCHAR(200) NOT NULL,
vegetarian BOOLEAN DEFAULT FALSE,
picked_up BOOLEAN DEFAULT FALSE,
PRIMARY KEY (id)
);